# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-7c9856cc-c7df-428b-8b55-f8c9f2c6e46f";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-7c9856cc-c7df-428b-8b55-f8c9f2c6e46f".device = "/dev/disk/by-uuid/7c9856cc-c7df-428b-8b55-f8c9f2c6e46f";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/8FDA-AB28";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-68cd8be7-08ff-45ad-a888-a23dc0800fed"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
